baseURL = "http://jesustorres.es/"
defaultContentLanguage = "es"
languageCode = "es"
title = "Jesús Torres"

theme = "LoveIt"

# Actualizar el lastmod de cada página usando la fecha del commit
enableGitInfo = true
enableEmoji = true

[params]
  # Necesario para activar LoveIt
  version = "0.2.X"
[params.page]
  # Mapbox GL JS config
  [params.page.mapbox]
    accessToken = "pk.eyJ1Ijoiam10b3JyZXMiLCJhIjoiY2tiZjhqZTB4MG44bzMwcDJxczlobTVncSJ9.7jnnoY0OkW-cw5WOYq0mag"
    lightStyle = "mapbox://styles/mapbox/light-v10"
    darkStyle = "mapbox://styles/mapbox/dark-v10"
    navigation = true
    geolocate = true
    scale = true
    fullscreen = true


[taxonomies]
#  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
